events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name projet1.example.com;

        location / {
            proxy_pass http://projet1_apache:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name projet2.example.com;

        location / {
            proxy_pass http://projet2_apache:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name projet3.example.com;

        location / {
            proxy_pass http://projet3_apache:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
