events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name projet1.example.com;

        location / {
            proxy_pass http://10.113.43.222:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name projet2.example.com;

        location / {
            proxy_pass http://<IP_PROJET2_APACHE_LXD>:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name projet3.example.com;

        location / {
            proxy_pass http://<IP_PROJET3_APACHE_LXD>:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
